version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=iceScrum
      - MYSQL_ROOT_PASSWORD=iceScrum
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  icescrum:
    image: icescrum/icescrum
    volumes:
      - ./home:/root
    environment:
      - ICESCRUM_HTTPS_PROXY=true
      - ICESCRUM_CONTEXT=/
    ports:
      - "8082:8080"
    depends_on:
      - mysql
